server:
  port: 8001
eureka:
  instance:                   #定义Eureka实例
    hostname: eureka-8001.com #Eureka实例所在的主机名
spring:
  #eureka默认情况下,把自己当做客户端来注册自己,所以我们要禁用它
  client:
    register-with-eureka: false #表示是否将自己注册到Eureka Server上，默认为true 
    fetch-registry: false       #表示是否从Eureka Server上获取注册信息，默认为true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      server:
    eviction-interval-timer-in-ms: 5000 #清理间隔（单位毫秒，默认是60*1000）
    enable-self-preservation: true # 默认为true。设为false，关闭自我保护。
    # Eureka Server 在运行期间会去统计心跳失败比例在 15 分钟之内是否低于 85%
    renewal-percent-threshold: 0.1 # 默认是0.85