spring:
  application:
    name: gateway

  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
      routes:
      - id: user
        uri: lb://user
        predicates:
        - Path=/api-a/**
        filters:
        - StripPrefix=1 #过滤的路径层级
  profiles:
    active: prod1

#gateway:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
  